name: TypeCheck CI

on:
  push:

jobs:
  Mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: pipx install uv
        shell: bash

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - run: uv install
        shell: bash

      - name: Run Mypy
        shell: bash
        run: |
          uv run mypy ./nonebot_plugin_nonechat
